INSERT INTO ELIGIBILITY_DTLS  (ELIG_ID,  CASE_NUM , PLAN_NAME, PLAN_STATUS,  HOLDER_NAME , HOLDER_SSN , BENIFIT_AMT, START_DATE, END_DATE ,DENIAL_REASON)   VALUES (101, 1, 'SNAP' ,  'Approved' , 'RAJ MALOTRA' ,842222, 8063.23 , '2022-05-22' , '2022-06-22' , NULL);
INSERT INTO ELIGIBILITY_DTLS  (ELIG_ID,  CASE_NUM , PLAN_NAME, PLAN_STATUS,  HOLDER_NAME , HOLDER_SSN , BENIFIT_AMT, START_DATE, END_DATE ,DENIAL_REASON)   VALUES (102, 2, 'SNAP' ,  'Approved' , 'RAMESH MALOTRA' ,852222, 80853.23 , '2022-05-21' , '2022-06-21' , NULL);
INSERT INTO ELIGIBILITY_DTLS  (ELIG_ID,  CASE_NUM , PLAN_NAME, PLAN_STATUS,  HOLDER_NAME , HOLDER_SSN , BENIFIT_AMT, START_DATE, END_DATE ,DENIAL_REASON)   VALUES (103, 3, 'SNAP' ,  'Denied' , 'RAJ WARMA' , 899, 4525, NULL, NULL, 'HIGH SALARY INCOME' );
INSERT INTO ELIGIBILITY_DTLS  (ELIG_ID,  CASE_NUM , PLAN_NAME, PLAN_STATUS,  HOLDER_NAME , HOLDER_SSN , BENIFIT_AMT, START_DATE, END_DATE ,DENIAL_REASON)   VALUES (104, 4, 'SNAP' ,  'Denied' , 'ROHIT SHETTY' , 5852, 25424 , NULL, NULL , 'HIGH RENT INCOME');



INSERT INTO ELIGIBILITY_DTLS  (ELIG_ID,  CASE_NUM , PLAN_NAME, PLAN_STATUS,  HOLDER_NAME , HOLDER_SSN , BENIFIT_AMT, START_DATE, END_DATE ,DENIAL_REASON)   VALUES (105, 1, 'CCAP'  ,  'Approved' , 'RAJASHRI' , 842222, 8063.23 , '2022-05-22' , '2022-06-22' , NULL);
INSERT INTO ELIGIBILITY_DTLS  (ELIG_ID,  CASE_NUM , PLAN_NAME, PLAN_STATUS,  HOLDER_NAME , HOLDER_SSN , BENIFIT_AMT, START_DATE, END_DATE ,DENIAL_REASON)   VALUES (106, 2, 'CCAP'  ,  'Approved' , 'SHITAL' ,852222, 80853.23 , '2022-05-21' , '2022-06-21' , NULL);
INSERT INTO ELIGIBILITY_DTLS  (ELIG_ID,  CASE_NUM , PLAN_NAME, PLAN_STATUS,  HOLDER_NAME , HOLDER_SSN , BENIFIT_AMT, START_DATE, END_DATE ,DENIAL_REASON)   VALUES (107, 3, 'CCAP'  ,  'Denied' , 'RANI' ,8992295,52285,NULL,NULL ,'Kids Not Available');
INSERT INTO ELIGIBILITY_DTLS  (ELIG_ID,  CASE_NUM , PLAN_NAME, PLAN_STATUS,  HOLDER_NAME , HOLDER_SSN , BENIFIT_AMT, START_DATE, END_DATE ,DENIAL_REASON)   VALUES (108, 4, 'CCAP'  ,  'Denied' , 'RAJANI SHETTY' , 87522 ,254242, NULL, NULL ,'HIGH RENT INCOME');



INSERT INTO ELIGIBILITY_DTLS  (ELIG_ID,  CASE_NUM , PLAN_NAME, PLAN_STATUS,  HOLDER_NAME , HOLDER_SSN , BENIFIT_AMT, START_DATE, END_DATE ,DENIAL_REASON)   VALUES (109, 1, 'Medicaid' ,  'Approved' , 'RAJ MALOTRA' ,842222, 8063.23 , '2022-05-22' , '2022-06-22' , NULL);
INSERT INTO ELIGIBILITY_DTLS  (ELIG_ID,  CASE_NUM , PLAN_NAME, PLAN_STATUS,  HOLDER_NAME , HOLDER_SSN , BENIFIT_AMT, START_DATE, END_DATE ,DENIAL_REASON)   VALUES (1010, 2, 'Medicaid' ,  'Approved' , 'RAMESH MALOTRA' ,852222, 80853.23 , '2022-05-21' , '2022-06-21' , NULL);
INSERT INTO ELIGIBILITY_DTLS  (ELIG_ID,  CASE_NUM , PLAN_NAME, PLAN_STATUS,  HOLDER_NAME , HOLDER_SSN , BENIFIT_AMT, START_DATE, END_DATE ,DENIAL_REASON)   VALUES (1011, 3, 'Medicaid' ,  'Denied' , 'RAJANIKANT  WARMA' ,899222, 15212, NULL,NULL , 'Age not matching');
INSERT INTO ELIGIBILITY_DTLS  (ELIG_ID,  CASE_NUM , PLAN_NAME, PLAN_STATUS,  HOLDER_NAME , HOLDER_SSN , BENIFIT_AMT, START_DATE, END_DATE ,DENIAL_REASON)   VALUES (1012, 4, 'Medicaid' ,  'Denied' , 'ROHIT SHETTY' ,8722 ,65323,NULL,NULL , 'Kids Age Above 16 Years');
 


  
INSERT INTO ELIGIBILITY_DTLS  (ELIG_ID,  CASE_NUM , PLAN_NAME, PLAN_STATUS,  HOLDER_NAME , HOLDER_SSN , BENIFIT_AMT, START_DATE, END_DATE ,DENIAL_REASON)   VALUES (1013, 1,   'Medicare' , 'Approved'  , 'RAMESH MALOTRA' ,842222, 8063.23 , '2022-05-22' , '2022-06-22' , NULL);
INSERT INTO ELIGIBILITY_DTLS  (ELIG_ID,  CASE_NUM , PLAN_NAME, PLAN_STATUS,  HOLDER_NAME , HOLDER_SSN , BENIFIT_AMT, START_DATE, END_DATE ,DENIAL_REASON)   VALUES (1014, 2,  'Medicare' , 'Approved',   'AACHAL MALOTRA' ,852222, 80853.23 , '2022-05-21' , '2022-06-21' , NULL);
INSERT INTO ELIGIBILITY_DTLS  (ELIG_ID,  CASE_NUM , PLAN_NAME, PLAN_STATUS,  HOLDER_NAME , HOLDER_SSN , BENIFIT_AMT, START_DATE, END_DATE ,DENIAL_REASON)   VALUES (1015, 3,  'Medicare' ,'Denied' , 'DEEPAK' ,899222 ,74474,NULL,NULL  ,'High Income');
INSERT INTO ELIGIBILITY_DTLS  (ELIG_ID,  CASE_NUM , PLAN_NAME, PLAN_STATUS,  HOLDER_NAME , HOLDER_SSN , BENIFIT_AMT, START_DATE, END_DATE ,DENIAL_REASON)   VALUES (1016, 4,  'Medicare' , 'Denied' , 'ALOK' ,8722 ,4747,NULL,NULL  , 'High Property Income');
 
  
  
INSERT INTO ELIGIBILITY_DTLS  (ELIG_ID,  CASE_NUM , PLAN_NAME, PLAN_STATUS,  HOLDER_NAME , HOLDER_SSN , BENIFIT_AMT, START_DATE, END_DATE ,DENIAL_REASON)   VALUES (1017, 1, 'QHP',  'Approved'  ,  'RAMESH MALOTRA' ,842222, 8063.23 , '2022-05-22' , '2022-06-22' , NULL);
INSERT INTO ELIGIBILITY_DTLS  (ELIG_ID,  CASE_NUM , PLAN_NAME, PLAN_STATUS,  HOLDER_NAME , HOLDER_SSN , BENIFIT_AMT, START_DATE, END_DATE ,DENIAL_REASON)   VALUES (1018, 2, 'QHP',   'Approved'  ,  'AACHAL MALOTRA' ,852222, 80853.23 , '2022-05-21' , '2022-06-21' , NULL);
INSERT INTO ELIGIBILITY_DTLS  (ELIG_ID,  CASE_NUM , PLAN_NAME, PLAN_STATUS,  HOLDER_NAME , HOLDER_SSN , BENIFIT_AMT, START_DATE, END_DATE ,DENIAL_REASON)   VALUES (1019, 3, 'QHP',  'Denied' , 'DEEPAK' ,899222 , 4747, NULL, NULL ,'High Income');
INSERT INTO ELIGIBILITY_DTLS  (ELIG_ID,  CASE_NUM , PLAN_NAME, PLAN_STATUS,  HOLDER_NAME , HOLDER_SSN , BENIFIT_AMT, START_DATE, END_DATE ,DENIAL_REASON)   VALUES (1020, 4, 'QHP',    'Denied' ,  'ALOK' ,8722255 , 4747, NULL, NULL, 'High Property Income');
 
  

 
 
 
  
  

 
  
  

 
 